name             'zip_hdfs'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures zip_hdfs'
long_description 'Installs/Configures zip_hdfs'
version          '0.2.2'

depends 'java'
depends 'hadoop'
